var annotated_dup =
[
    [ "AirHumidifier", "class_air_humidifier.html", null ],
    [ "AirHumiditySensor", "class_air_humidity_sensor.html", null ],
    [ "BaseDevice", "class_base_device.html", null ],
    [ "BaseSensor", "class_base_sensor.html", null ],
    [ "ClimateManager", "class_climate_manager.html", null ],
    [ "Conditioner", "class_conditioner.html", null ],
    [ "ConfigManager", "class_config_manager.html", null ],
    [ "ExtendedConfigManager", "class_extended_config_manager.html", null ],
    [ "Heater", "class_heater.html", null ],
    [ "IAdjustableDevice", "class_i_adjustable_device.html", null ],
    [ "IClimateManager", "class_i_climate_manager.html", null ],
    [ "IConfigManager", "class_i_config_manager.html", null ],
    [ "IDataProvider", "class_i_data_provider.html", null ],
    [ "IDevice", "class_i_device.html", null ],
    [ "IIOManager", "class_i_i_o_manager.html", null ],
    [ "IModeSelectableDevice", "class_i_mode_selectable_device.html", null ],
    [ "IOManager", "class_i_o_manager.html", null ],
    [ "IRegulator", "class_i_regulator.html", null ],
    [ "Irrigation", "class_irrigation.html", null ],
    [ "ISensor", "class_i_sensor.html", null ],
    [ "ISimulationEngine", "class_i_simulation_engine.html", null ],
    [ "Lamp", "class_lamp.html", null ],
    [ "OnOffRegulator", "class_on_off_regulator.html", null ],
    [ "PidRegulator", "class_pid_regulator.html", null ],
    [ "SafetyProxyManager", "class_safety_proxy_manager.html", null ],
    [ "ScheduleConfig", "struct_schedule_config.html", null ],
    [ "SimulationEngine", "class_simulation_engine.html", null ],
    [ "SimulationModel", "class_simulation_model.html", null ],
    [ "SoilMoistureSensor", "class_soil_moisture_sensor.html", null ],
    [ "TemperatureSensor", "class_temperature_sensor.html", null ],
    [ "TimerSchedule", "class_timer_schedule.html", null ],
    [ "Ventilation", "class_ventilation.html", null ]
];