var files_dup =
[
    [ "AirHumidifier.h", "_air_humidifier_8h_source.html", null ],
    [ "AirHumiditySensor.h", "_air_humidity_sensor_8h_source.html", null ],
    [ "BaseDevice.h", "_base_device_8h_source.html", null ],
    [ "BaseSensor.h", "_base_sensor_8h_source.html", null ],
    [ "ClimateManager.h", "_climate_manager_8h_source.html", null ],
    [ "Conditioner.h", "_conditioner_8h_source.html", null ],
    [ "ConfigManager.h", "_config_manager_8h_source.html", null ],
    [ "Heater.h", "_heater_8h_source.html", null ],
    [ "IClimateManager.h", "_i_climate_manager_8h_source.html", null ],
    [ "IConfigManager.h", "_i_config_manager_8h_source.html", null ],
    [ "IDataProvider.h", "_i_data_provider_8h_source.html", null ],
    [ "IDevice.h", "_i_device_8h_source.html", null ],
    [ "IIOManager.h", "_i_i_o_manager_8h_source.html", null ],
    [ "IOManager.h", "_i_o_manager_8h_source.html", null ],
    [ "IRegulator.h", "_i_regulator_8h_source.html", null ],
    [ "Irrigation.h", "_irrigation_8h_source.html", null ],
    [ "ISensor.h", "_i_sensor_8h_source.html", null ],
    [ "ISimulationEngine.h", "_i_simulation_engine_8h_source.html", null ],
    [ "Lamp.h", "_lamp_8h_source.html", null ],
    [ "OnOffRegulator.h", "_on_off_regulator_8h_source.html", null ],
    [ "PidRegulator.h", "_pid_regulator_8h_source.html", null ],
    [ "SafetyProxyManager.h", "_safety_proxy_manager_8h_source.html", null ],
    [ "ScheduleConfig.h", "_schedule_config_8h_source.html", null ],
    [ "SimulationEngine.h", "_simulation_engine_8h_source.html", null ],
    [ "SimulationModel.h", "_simulation_model_8h_source.html", null ],
    [ "SoilMoistureSensor.h", "_soil_moisture_sensor_8h_source.html", null ],
    [ "TemperatureSensor.h", "_temperature_sensor_8h_source.html", null ],
    [ "TimerSchedule.h", "_timer_schedule_8h_source.html", null ],
    [ "Ventilation.h", "_ventilation_8h_source.html", null ]
];